### ISSUE TITLE
Support for JupyterLab 3.0

### ISSUE THREAD

**Issue by jtpio** [jupytercalpoly/jupyterlab-interactive-dashboard-editor#102]
With JupyterLab 3.0 final now available, it would be nice to make the extension compatible with it.

Using the new distribution system would also make it easier to install with `pip` and `conda`.

Thanks!

**Comment by jtpio** [comment]
Linking to a couple of resources that might help get this started:

- Using the upgrade script: https://jupyterlab.readthedocs.io/en/stable/extension/extension_migration.html#upgrading-library-versions-using-the-upgrade-script
- Extension tutorial using the Python packaging for distributing the extension: https://jupyterlab.readthedocs.io/en/stable/extension/extension_tutorial.html
- Docs on the prebuilt extensions: https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#prebuilt-extensions

**Comment by cameron-toy** [comment]
Thanks Jeremy, I'll get right on this. Those resources are extremely helpful!

**Comment by cameron-toy** [comment]
Addressed by PR #104!
