### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by ndgayan** [jupytercalpoly/jupyterlab-interactive-dashboard-editor#118]
When I try to install, I'm getting bellow error

ERROR: Could not find a version that satisfies the requirement jupyterlab_interactive_dashboard_editor (from versions: none)
ERROR: No matching distribution found for jupyterlab_interactive_dashboard_editor

Below is my lab specs:
jupyter core     : 4.7.1
jupyter-notebook : 6.2.0
qtconsole        : not installed
ipython          : 7.21.0
ipykernel        : 5.5.0
jupyter client   : 6.1.12
jupyter lab      : 3.0.11
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.2
traitlets        : 5.0.5

and the pip version is 20.0.2

Please take a look this issue.

**Comment by krassowski** [comment]
Looks like it has not been published to PyPI: https://pypi.org/search/?q=jupyterlab_interactive_dashboard_editor :(

It is a security issue @juliahuynh @cameron-toy. If someone beats you to publishing, you might find yourself recommending installation of a malware package in the README.

**Comment by Zsailer** [comment]
Good catch. Thanks, @krassowski. We should move on this ASAP. 

@cameron-toy, can you try publishing this PyPI when you get a chance? Then, would you mind adding me as a maintainer on the PyPI package. Let me know if you need help with publishing.

**Comment by krassowski** [comment]
A minor point, the package name would ideally be `jupyterlab-interactive-dashboard-editor` as per PEP8:

> Python packages should also have short, all-lowercase names, although the use of underscores is discouraged.

I can send a PR on Thursday evening.

**Comment by krassowski** [comment]
Actually today evening was fine too. #121 is ready for review.

**Comment by krassowski** [comment]
Thanks for merging @cameron-toy! I believe it would be really good to make a release to PyPI now (maybe after a version bump first). I can help with this if you wish. All you need to do is:

a) Register for an account on PyPI: https://pypi.org/account/register/

b) Package the extension with the following command:

```bash
python3 -m pip install --upgrade pip build twine jupyterlab
python3 -m build
```

c) Upload it to test PyPI to check if it looks ok:

```
python3 -m twine --repository testpypi upload dist/*
```

d) Perform the final upload:

```
python3 -m twine upload dist/*
```

See:
- https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives
- https://github.com/jupytercalpoly/jupyterlab-tabular-data-editor/blob/master/.github/workflows/publish.yml

Once you published the first release to PyPI I highly recommend to setup `publish.yml` (as linked above) to automate releases.

**Comment by cameron-toy** [comment]
@krassowski Thank you for such complete instructions! I really appreciate the help.

Sorry for the late reply--I've been off from work and haven't had a chance to work on this repo. I start again tomorrow and I will have the package updated and published by 2pm PST!

**Comment by cameron-toy** [comment]
Extension is on PyPi and installation should work now

**Comment by krassowski** [comment]
Thank you! I can confirm that installation form PyPI works at my end.
