### ISSUE TITLE
Gif on README

### ISSUE THREAD

**Issue by echarles** [jupytercalpoly/jupyterlab-interactive-dashboard-editor#45]
It would be great to have an animated GIF on the README to preview the developed features. As fallback, a text description on how to use would be an option.

I could build and try to discover, but the GIF/TXT would be more welcoming to me to take that step.

**Comment by Zsailer** [comment]
I agree with @echarles on this. A `.gif` showing how to open and start using the dashboard would really attract users. I think you're going to get a lot of traffic to this extension. Even if the extension isn't finished, getting users to try it out early will help you get feedback on how to improve moving forward. 

Also, have y'all tried building a binder for this yet?

**Comment by Zsailer** [comment]
Looks like this was merged in #46

**Comment by echarles** [comment]
Yeah. Thx a lot for this. The GIF shows what it is. In the meantime, I have installed the extensions and it holds its promises. Have not yet gone to the dashboard saving/loading. Will give it another try between a few other things.
