### ISSUE TITLE
Icon for dashboard

### ISSUE THREAD

**Issue by cameron-toy** [jupytercalpoly/jupyterlab-interactive-dashboard-editor#7]
Dashboards are currently displayed with the same icon as notebooks. I think it'd be good to have a unique icon to differentiate them.

I believe JupyterLab uses `.svg` files for icons.

**Comment by juliahuynh** [comment]
working on it!

**Comment by juliahuynh** [comment]
First iteration of dashboard icons:
- Material Design based
- 20dp x 20dp for dense desktop view
- Blue icon is for use in the tab icon
- White outline icon is for use in the table of contents when file is selected
- Grey versions are for other purposes (TBD)


![Screen Shot 2020-06-30 at 4 04 36 PM](https://user-images.githubusercontent.com/49352608/86185548-6e5eaa00-baeb-11ea-9809-f675bb3b844f.png)
